### ISSUE TITLE
Release memory

### ISSUE THREAD

**Issue by inokawa** [inokawa/three-sandbox#2]
unmount時に適切にdisposeしたい
https://threejs.org/docs/#manual/en/introduction/How-to-dispose-of-objects

**Comment by n-inokawa** [comment]
素直にVueなどで組むのもあり

**Comment by n-inokawa** [comment]
https://threejsfundamentals.org/threejs/lessons/threejs-cleanup.html

**Comment by inokawa** [comment]
https://github.com/inokawa/three-sandbox/commit/ad9b6873384812f9eec088afbb7fdc891a2a0651
